; PlatformIO - Painel LED Lambda (WS2812B 8x8 / CJMCU-64)
; Grave com o gravar.bat na raiz:  gravar.bat [micro|nano|nanoold]
;   micro    -> Arduino Micro (ATmega32U4)      [padrao]
;   nano     -> Arduino Nano bootloader NOVO (optiboot, 115200)
;   nanoold  -> Arduino Nano bootloader ANTIGO (57600) - clones mais antigos

[common]
framework     = arduino
monitor_speed = 115200
lib_deps      = fastled/FastLED @ ^3.6.0

[env:micro]
platform      = atmelavr
board         = micro
framework     = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps      = ${common.lib_deps}
upload_speed  = 115200

[env:nano]
platform      = atmelavr
board         = nanoatmega328new     ; bootloader novo (Optiboot)
framework     = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps      = ${common.lib_deps}
upload_speed  = 115200

[env:nanoold]
platform      = atmelavr
board         = nanoatmega328        ; bootloader antigo
framework     = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps      = ${common.lib_deps}
upload_speed  = 57600
